# Generated by Django 6.0 on 2026-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='extracted_text_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
